// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/18/2026, 2:49:35 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/leighdinaya/Web/Nuxt/local-share-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/plugins/**/*.{js,ts,mjs}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/composables/**/*.{js,ts,mjs}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/utils/**/*.{js,ts,mjs}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;