// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/31/2025, 10:20:29 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/leighdinaya/Web/Nuxt/local-share-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","<rootDir>/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","<rootDir>/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/plugins/**/*.{js,ts,mjs}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/composables/**/*.{js,ts,mjs}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/utils/**/*.{js,ts,mjs}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/leighdinaya/Web/Nuxt/local-share-app/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;